/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemas.GUI;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.ResultSet;
import java.util.Arrays;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import sistemas.controllers.ControllerEMPRESAS;
import sistemas.models.modelEMPRESA;
import sistemas.libs.LeerExcel;

/**
 *
 * @author USUARIO
 */
public class frmInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    DefaultTableModel modelo;

    public frmInicio() {
        initComponents();

        txtid.setEditable(false);
        panelAuditor.setVisible(true);

        btnnotascredito.setEnabled(false);
        btnnotacreditocompras.setEnabled(false);
        btnordenesdepago.setEnabled(false);

        String[] titulos = {"ID", "Nit", "Razon social", "Direccion", "Correo"};
        modelo = new DefaultTableModel(null, titulos);

        tblempresas.setModel(modelo);

        this.mostrarDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnit = new javax.swing.JTextField();
        lbnotification = new javax.swing.JLabel();
        txtrazonsocial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblempresas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btneliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();
        panelAuditor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JTPmodular = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        panelv = new javax.swing.JPanel();
        btnnotascredito = new javax.swing.JButton();
        btncargarventas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btncargarrecibos = new javax.swing.JButton();
        btnverVentas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnordenesdepago = new javax.swing.JButton();
        btnnotacreditocompras = new javax.swing.JButton();
        btncargarventas1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btnvolverventas6 = new javax.swing.JButton();
        btnverCausaciones = new javax.swing.JButton();
        btnverPagosdirectos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btncargarventas2 = new javax.swing.JButton();
        txtauditor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Correo");

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Direccion");

        lbnotification.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbnotification.setForeground(new java.awt.Color(255, 0, 0));
        lbnotification.setText("    ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Selector de empresas");

        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setContentAreaFilled(false);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btneditar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btneditar.setText("Editar");
        btneditar.setContentAreaFilled(false);
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        tblempresas.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tblempresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblempresas.setGridColor(new java.awt.Color(255, 255, 255));
        tblempresas.setOpaque(false);
        tblempresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblempresasMouseClicked(evt);
            }
        });
        tblempresas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblempresasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblempresas);

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("ID");

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Razon Social");

        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setContentAreaFilled(false);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("NIT");

        btncancelar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setContentAreaFilled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnTest.setText("test");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btneliminar)
                            .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtdireccion)
                        .addComponent(txtrazonsocial)
                        .addComponent(txtnit)
                        .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btneditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbnotification, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTest)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtrazonsocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btneditar)
                            .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btneliminar)
                            .addComponent(btncancelar)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lbnotification))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnTest)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelAuditor.setBackground(new java.awt.Color(255, 255, 255));
        panelAuditor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Modulos Para Auditar");

        JTPmodular.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        panelv.setBackground(new java.awt.Color(255, 255, 255));
        panelv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnnotascredito.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnnotascredito.setText("Cargar");
        btnnotascredito.setContentAreaFilled(false);

        btncargarventas.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btncargarventas.setText("Cargar");
        btncargarventas.setContentAreaFilled(false);
        btncargarventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarventasActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Cargue las Ventas");

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Cargue las Notas credito");

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Cargue los Recibos de caja");

        btncargarrecibos.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btncargarrecibos.setText("Cargar");
        btncargarrecibos.setContentAreaFilled(false);
        btncargarrecibos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarrecibosActionPerformed(evt);
            }
        });

        btnverVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemas/recursos/ver.png"))); // NOI18N
        btnverVentas.setBorder(null);
        btnverVentas.setBorderPainted(false);
        btnverVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelvLayout = new javax.swing.GroupLayout(panelv);
        panelv.setLayout(panelvLayout);
        panelvLayout.setHorizontalGroup(
            panelvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelvLayout.createSequentialGroup()
                .addGroup(panelvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addGroup(panelvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncargarrecibos)
                    .addComponent(btnnotascredito)
                    .addComponent(btncargarventas))
                .addGap(0, 452, Short.MAX_VALUE))
            .addGroup(panelvLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnverVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelvLayout.setVerticalGroup(
            panelvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelvLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncargarventas)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(btnnotascredito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(btncargarrecibos))
                .addGap(28, 28, 28)
                .addComponent(btnverVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        JTPmodular.addTab("VENTAS", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Cargue las Causaciones");

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Cargue las Notas credito");

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Cargue las Ordenes de Pago");

        btnordenesdepago.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnordenesdepago.setText("Cargar");
        btnordenesdepago.setContentAreaFilled(false);

        btnnotacreditocompras.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnnotacreditocompras.setText("Cargar");
        btnnotacreditocompras.setContentAreaFilled(false);

        btncargarventas1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btncargarventas1.setText("Cargar");
        btncargarventas1.setContentAreaFilled(false);
        btncargarventas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarventas1ActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Cargue los Pagos Directos");

        btnvolverventas6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnvolverventas6.setText("Cargar");
        btnvolverventas6.setContentAreaFilled(false);
        btnvolverventas6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverventas6ActionPerformed(evt);
            }
        });

        btnverCausaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemas/recursos/ver.png"))); // NOI18N
        btnverCausaciones.setBorder(null);

        btnverPagosdirectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemas/recursos/ver.png"))); // NOI18N
        btnverPagosdirectos.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnvolverventas6)
                        .addGap(18, 18, 18)
                        .addComponent(btnverPagosdirectos))
                    .addComponent(btnordenesdepago)
                    .addComponent(btnnotacreditocompras)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btncargarventas1)
                        .addGap(18, 18, 18)
                        .addComponent(btnverCausaciones)))
                .addContainerGap(526, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btncargarventas1)
                        .addComponent(jLabel9))
                    .addComponent(btnverCausaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(btnnotacreditocompras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(btnordenesdepago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(btnvolverventas6))
                    .addComponent(btnverPagosdirectos))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        JTPmodular.addTab("COMPRAS", jPanel3);

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Cargue la Nomina");

        btncargarventas2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btncargarventas2.setText("Cargar");
        btncargarventas2.setContentAreaFilled(false);
        btncargarventas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarventas2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(70, 70, 70)
                .addComponent(btncargarventas2)
                .addContainerGap(564, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncargarventas2)
                    .addComponent(jLabel14))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        JTPmodular.addTab("NOMINA", jPanel4);

        txtauditor.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        txtauditor.setText("Registrar Auditor");
        txtauditor.setContentAreaFilled(false);
        txtauditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtauditorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAuditorLayout = new javax.swing.GroupLayout(panelAuditor);
        panelAuditor.setLayout(panelAuditorLayout);
        panelAuditorLayout.setHorizontalGroup(
            panelAuditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAuditorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtauditor, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAuditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTPmodular)
                .addGap(24, 24, 24))
        );
        panelAuditorLayout.setVerticalGroup(
            panelAuditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAuditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAuditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtauditor)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(JTPmodular, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JTPmodular.getAccessibleContext().setAccessibleName("tab1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAuditor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelAuditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncargarventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarventasActionPerformed

        JFileChooser arc = new JFileChooser();
        arc.showOpenDialog(null);

        //seleccionamos el selector
        File arc2 = arc.getSelectedFile();
        // creamos una instancia de la libreria que se encargara de leer el archivo
        LeerExcel enviar = new LeerExcel();

        modelEMPRESA datos = validador();
        int IDEmpresa = datos.getID();

        if (IDEmpresa != 0) {
            // invocamos el metodo que procesara el archivo y mandara los datos a la base de datos
            enviar.incertarVentas(arc2, IDEmpresa);
        } else {
            lbnotification.setText("debes elegir una amepresa para cargarle los datos");
            lbnotification.setBackground(Color.red);
        }
    }//GEN-LAST:event_btncargarventasActionPerformed

    private void txtauditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtauditorActionPerformed
        // TODO add your handling code here:
        JFrame f = new frmEmpleados();
        f.setVisible(true);
    }//GEN-LAST:event_txtauditorActionPerformed

    private void tblempresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblempresasMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            txtid.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txtnit.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            txtrazonsocial.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
            txtdireccion.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
            txtcorreo.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 4).toString());
        }

        btnguardar.setEnabled(false);
        btneditar.setEnabled(true);
        btneliminar.setEnabled(true);
    }//GEN-LAST:event_tblempresasMouseClicked

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        modelEMPRESA datos = validador();

        ControllerEMPRESAS query = new ControllerEMPRESAS();
        query.queryDelete(datos.getID());

        this.limpiar();
        this.mostrarDatos();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        modelEMPRESA datos = validador();

        ControllerEMPRESAS query = new ControllerEMPRESAS();

        query.queryUpdate(datos.getID(), datos.getNit(), datos.getRazonsocial(), datos.getDireccion(), datos.getCorreo());

        this.limpiar();
        this.mostrarDatos();
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        modelEMPRESA datos = validador();

        ControllerEMPRESAS query = new ControllerEMPRESAS();
        query.queryIncert(datos.getNit(), datos.getRazonsocial(), datos.getDireccion(), datos.getCorreo());

        this.limpiar();
        this.mostrarDatos();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btncargarventas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarventas1ActionPerformed
        // CUENTAS POR PAGAR - CAUSACIONES
        JFileChooser arc = new JFileChooser();
        arc.showOpenDialog(null);

        //seleccionamos el selector
        File arc2 = arc.getSelectedFile();
        // creamos una instancia de la libreria que se encargara de leer el archivo
        LeerExcel enviar = new LeerExcel();

        modelEMPRESA datos = validador();
        int IDEmpresa = datos.getID();

        if (IDEmpresa != 0) {
            // invocamos el metodo que procesara el archivo y mandara los datos a la base de datos
            enviar.incertarComprasCxP(arc2, IDEmpresa);
        } else {
            lbnotification.setText("debes elegir una amepresa para cargarle los datos");
            lbnotification.setBackground(Color.red);
        }

    }//GEN-LAST:event_btncargarventas1ActionPerformed

    private void btncargarventas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarventas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncargarventas2ActionPerformed

    private void btncargarrecibosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarrecibosActionPerformed
        JFileChooser arc = new JFileChooser();
        arc.showOpenDialog(null);

        //seleccionamos el selector
        File arc2 = arc.getSelectedFile();
        // creamos una instancia de la libreria que se encargara de leer el archivo
        LeerExcel enviar = new LeerExcel();

        modelEMPRESA datos = validador();
        int IDEmpresa = datos.getID();

        if (IDEmpresa != 0) {
            // invocamos el metodo que procesara el archivo y mandara los datos a la base de datos
            enviar.incertarRecibo(arc2, IDEmpresa);

        } else {
            lbnotification.setText("debes elegir una amepresa para cargarle los datos");
            lbnotification.setBackground(Color.red);
        }

    }//GEN-LAST:event_btncargarrecibosActionPerformed

    private void btnvolverventas6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverventas6ActionPerformed
        JFileChooser arc = new JFileChooser();
        arc.showOpenDialog(null);

        //seleccionamos el selector
        File arc2 = arc.getSelectedFile();
        // creamos una instancia de la libreria que se encargara de leer el archivo
        LeerExcel enviar = new LeerExcel();

        modelEMPRESA datos = validador();
        int IDEmpresa = datos.getID();

        if (IDEmpresa != 0) {
            // invocamos el metodo que procesara el archivo y mandara los datos a la base de datos
            enviar.incertarComprasPagosDirectos(arc2, IDEmpresa);

        } else {
            lbnotification.setText("debes elegir una amepresa para cargarle los datos");
            lbnotification.setBackground(Color.red);
        }
    }//GEN-LAST:event_btnvolverventas6ActionPerformed

    private void btnverVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverVentasActionPerformed
        JFrame f = new moduloVentas();
        f.setVisible(true);
    }//GEN-LAST:event_btnverVentasActionPerformed

    private void tblempresasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblempresasKeyPressed

        try {
            /* ESTE CONDICIONAL ES PARA DETECTAR CUANDO PRESIONEN LA TECLA ENTER
            CUANDO SE CAMBIE LOS DATOS DIRECTAMENTE EN LA TABLA AL PRESIONAR ENTER LO QUE SUCEDE
            ES QUE LOS DATOS SE COLOCARAN EN LOS INPUTS CORRESPONDIENTES Y ADICIONAL
            SE ACTUALIZARA LOS DATOS EN LA BASE DE DATOS SQLITE
            
             */
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

                JTable receptor = (JTable) evt.getSource();
                txtid.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
                txtnit.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
                txtrazonsocial.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
                txtdireccion.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
                txtcorreo.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 4).toString());

                modelEMPRESA datos = validador();
                ControllerEMPRESAS query = new ControllerEMPRESAS();
                query.queryUpdate(datos.getID(), datos.getNit(), datos.getRazonsocial(), datos.getDireccion(), datos.getCorreo());

            } else if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
                /* 
                    ESTE EVENTO ES ESCUCHADO CUANDO SE OPRIMA LA LETRA SUPRIMIR, LO QUE HACE ES
                    TOMAR LAS FILAS SELECCIONADAS Y SEGUN CUANTAS HAYA SE CREA UN BUBLE FOR
                    QUE EN CADA ITERACION IRA EJECUTANDO UN QUERY QUE ELIMINA DE BASE DE DATOS SEGUN
                    EL ID DE TOMADO DE CADA FILA
                 */

                // EL VALIDADOR ES INSTANCIADO PARA QUE VALIDE EL CADA ID QUE SE PRETENDE ELIMINAR
                modelEMPRESA datos = validador();
                // ES INSTANCIADO EL CONTROLADOR QUE EJECUTA EL QUERY DE ELIMINACION
                ControllerEMPRESAS query = new ControllerEMPRESAS();
                //SE INSTANCIA EL EVENTO DE LA CLASE TABLA PARA TOMAR LOS DATOS DE ELLA         
                JTable receptorrr = (JTable) evt.getSource();
                /* receptorrr.getSelectedRows().length;  -> ES PARA CONTAR CUANTAS FILAS FUERON SELECCIONADAS
                Integer.parseInt(receptorrr.getModel().getValueAt(receptorrr.getSelectedRows()[i],0).toString()) -> ES PARA TOMAR EL ID COMO UN STRING Y CONVERTIRLO A INT
                 */
                for (int i = 0; i < receptorrr.getSelectedRows().length; i++) {
                    datos.setID(Integer.parseInt(receptorrr.getModel().getValueAt(receptorrr.getSelectedRows()[i], 0).toString()));
                    query.queryDelete(datos.getID());
                    //System.out.println("ID filas seleccionadas : " + receptorrr.getModel().getValueAt(receptorrr.getSelectedRows()[i],0).toString());
                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }

        this.limpiar();
        this.mostrarDatos();


    }//GEN-LAST:event_tblempresasKeyPressed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed

    }//GEN-LAST:event_btnTestActionPerformed

    public void mostrarDatos() {

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        try {
            //   desde el controlador hace el query y envia los datos a la interfaz
            ControllerEMPRESAS data = new ControllerEMPRESAS();
            ResultSet datos = data.queryGetData();

            while (datos.next()) {

                Object[] oUsuario = {datos.getString("ID"), datos.getString("nit"), datos.getString("razonsocial"), datos.getString("direccion"), datos.getString("correo")};

                modelo.addRow(oUsuario);
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void limpiar() {
        txtid.setText("");
        txtnit.setText("");
        txtrazonsocial.setText("");
        txtdireccion.setText("");
        txtcorreo.setText("");

        btnguardar.setEnabled(true);
        btneditar.setEnabled(false);
        btneliminar.setEnabled(false);
    }

    // UTILIZA LOS MODELOS DE DATOS SETER Y GETERS
    public modelEMPRESA validador() {
        modelEMPRESA oEmpresa = new modelEMPRESA();

        int ID = (txtid.getText().isEmpty() ? 0 : Integer.parseInt(txtid.getText()));

        oEmpresa.setID(ID);
        oEmpresa.setNit(txtnit.getText());
        oEmpresa.setRazonsocial(txtrazonsocial.getText());
        oEmpresa.setDireccion(txtdireccion.getText());
        oEmpresa.setCorreo(txtcorreo.getText());

        return oEmpresa;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTPmodular;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncargarrecibos;
    private javax.swing.JButton btncargarventas;
    private javax.swing.JButton btncargarventas1;
    private javax.swing.JButton btncargarventas2;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnotacreditocompras;
    private javax.swing.JButton btnnotascredito;
    private javax.swing.JButton btnordenesdepago;
    private javax.swing.JButton btnverCausaciones;
    private javax.swing.JButton btnverPagosdirectos;
    private javax.swing.JButton btnverVentas;
    private javax.swing.JButton btnvolverventas6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbnotification;
    private javax.swing.JPanel panelAuditor;
    private javax.swing.JPanel panelv;
    private javax.swing.JTable tblempresas;
    private javax.swing.JButton txtauditor;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnit;
    private javax.swing.JTextField txtrazonsocial;
    // End of variables declaration//GEN-END:variables
}
